[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.17"
optimizer = true
optimizer_runs = 200

[profile.institutional]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.33"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

[etherscan]
gnosis = { key = "${GNOSISSCAN_API_KEY}", url = "https://api.gnosisscan.io/api" }